<a href="https://colab.research.google.com/github/mlabonne/how-to-data-science/blob/main/What_is_a_Tensor_in_Deep_Learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import torch

array = np.array([1, 2, 3])
print(f'NumPy Array: {array}')

tensor = torch.tensor([1, 2, 3])
print(f'PyTorch Tensor: {tensor}')

NumPy Array: [1 2 3]
PyTorch Tensor: tensor([1, 2, 3])


In [ ]:
array = np.array([[1, 2, 3],
                  [4, 5, 6]])
print(f'NumPy Array:\n{array}')

tensor = torch.tensor([[1, 2, 3],
                       [4, 5, 6]])
print(f'\nPyTorch Tensor:\n{tensor}')

NumPy Array:
[[1 2 3]
 [4 5 6]]

PyTorch Tensor:
tensor([[1, 2, 3],
        [4, 5, 6]])


In [ ]:
# You need to run this code on a computer with a GPU
device = torch.device("cuda")

# 4D arrays
array1 = np.random.rand(100, 100, 100, 100)
array2 = np.random.rand(100, 100, 100, 100)

# 4D tensors
tensor1 = torch.rand(100, 100, 100, 100).to(device)
tensor2 = torch.rand(100, 100, 100, 100).to(device)

In [ ]:
%%timeit
np.matmul(array1, array2)

1 loop, best of 5: 1.32 s per loop


In [ ]:
%%timeit
torch.matmul(tensor1, tensor2)

1000 loops, best of 5: 25.2 ms per loop
